export enum ResponseMessage {
  SUCCESS = 'Success',
  CREATED_SUCCESSFULLY = 'Created successfully',
  CONTENT_NOT_FOUND = 'Content not found',
  PLEASE_LOGIN_WITH = 'Please Login With : ',
  INVALID_USERNAME_OR_PASSWORD = 'Invalid email or password', // both admin and customer
  USER_ALREADY_EXISTS = 'User with the same email already exists', // both admin and customer
  FORGOT_PASSWORD_EMAIL = 'Please Check Your Email To Reset Password',
  EMAIL_NOT_REGISTERED = 'Email not registered', // both admin and customer
  EMAIL_NOT_VERIFIED = 'Email not verified',
  EMAIL_CODE_EXPIRED = 'Email verification code Has Been Expired',
  INVALID_EMAIL = 'Invalid email address',
  INVALID_PASSWORD = 'Please check the password conditions',
  INVALID_USERNAME = 'Invalid user name',
  INVALID_NAME = 'Invalid name',
  INVALID_COUNTRY = 'Invalid country name',
  INVALID_PHONE_NUMBER = 'Phone number is not valid',
  INVALID_VERIFICATION_CODE = 'Invalid verification code',
  INVALID_AGE = 'Invalid age',
  RESET_PASSWORD_CODE_EXPIRED = 'This Reset Password Code Has Been Expied',
  RESET_PASSWORD_LINK_EXPIRED = 'This Reset Password Link Has Been Expied',
  USER_DOES_NOT_EXIST = 'User with specified email does not exists',
  EMAIL_QUERY_PARAM_MISSING = "Param 'email' missing",
  INVALID_EMIAIL_VERIFICATION_CODE = 'Invalid email verification code',
  INVALID_PHONE_NUMBER_CODE = 'Invalid phone number code',
  PASSWORD_NOT_MATCH = 'Password do not match',
  SPECIAL_CHAR_NOT_ALLOWED = 'Special characters are not allowed',
  INVALID_NICKNAME = 'Invalid nick name',
  NICKNAME_ALREADY_EXIST = 'This nickname is already taken',
  NICKNAME_CAN_BE_USE = 'It’s possible to use',
  ERROR_WHILE_SENDING_MESSAGE = 'There was some error in sending your message. Please try again',
  EMAIL_SENDING_ERROR = 'There was some error in sending your email. Please try again',
  INVALID_REFERRAL_CODE = 'The referral code is invalid',
  REFERRER_NOT_EXIST = 'Referrar does not exist',
  TOKEN_DOES_NOT_EXIST = 'Token does not exist',
  PHONE_NUMBER_ALREADY_IN_USE = 'Phone number already registered',
  PHONE_NUMBER_VERIFIED = 'Phone number verified',
  CERTIFIED = 'certified',
  TOKEN_EXPIRED = 'token is expired',
  INVALID_TOKEN = 'invalid token', // both admin and customer
  UNABLE_TO_SOCIAL_LOGIN = 'Unable to login via social',
  UNABLE_TO_PING_EXCHANGE_SERVICE = 'Unable to ping exchange service',
  USER_PHONE_NUMBER_UPDATE_FAILED = 'Error in updating phone number',
  OTP_VERIFICATION_FAILED = 'OTP verification failed',
  SENDING_OTP_FAILED = 'Could not send otp',
  FIVE_LOGIN_ATTEMPT = 'Password error 5 times, You cannot login for 24 hours',
  DEVICE_ALREADY_EXIST = 'Device Id already Exist',
  MEMBERSHIP_EXPIRY_FOR_SIX_MONTH = 'Registration is not possible for 6 months after membership withdrawal',
  INCORRECT_CURRENT_PASS = 'Your current password is incorrect',
  SAME_AS_OLD_PASS = 'Same as current password',
  PASS_CHANGE_SUCCESS = 'Password change is complete',
  SURVEY_NOT_EXIST = 'Survey does not exist',
  SURVEY_OPTION_NOT_EXIST = 'Survey option does not exist',
  SOT_NOT_EXIST = 'sot does not exist',
  INVALID_QUERY_PARAM = 'Invalid query parameter',
  WALLET_NOT_EXIST = 'User wallet does not exist',
  BALANCE_LESS_THAN_REQUIRED = 'Your current balance is less than required',
  UNAUTHORIZED_TO_EDIT_SURVEY = 'Only Initiator can edit survey',
  INVALID_SOT_ID = 'Invalid Sot Id',
  INVALID_OPTION_ID = 'Invalid Option Id',
  INTERNAL_ERROR = 'Internal Error',
  INVALID_LOGIN_TYPE = 'Invalid Login Type',
  IMAGES_ALLOW = 'Only jpg and png images are allowed',
  IMAGE_REQUIRED = 'Image Is Empty / Invalid',
  INVALID_FILE_FORMAT = 'Invalid File Format. Please select image for relevant fields.',
  INVALID_S3_KEY = 'Invalid Image Key',
  S3_KEY_NOT_EXIST = 'Key does not exist',
  END_DATE_GREATER_THAN_START = 'Ending date must be greater than starting date',
  PASSWORD_ALREADY_CREATED = 'Password already set',
  PAYMENT_ALREADY_MAKE = 'Survey payment already make',
  FIVE_PHONE_CODE_SEND = 'Phone code send error 5 times',
  TEMPORARY_BLOCK = 'You Account has been blocked temparory.Kindly contact Admin via support',
  FIVE_CONFIRMATION_ATTEMPT = 'Confirmation attempt error 5 times, You cannot send verification code for 30 minutes',
  PARTICIPATED_IN_SURVEY = 'Participated in survey',
  PARTICIPATED_COUNT_COMPLETED = 'Participate limit completed',
  INITIATOR_CAN_NOT_PARTICIPATE = 'Initialor can not Participate',
  NOT_PARTICIPATED = 'User not participated',
  COMMENT_ALREADY_ADDED = 'comment already added',
  COMMENT_NOT_EXIST = 'Comment not exists ',
  ONLY_COMMENT_INITIATOR_CAN_DELETE = 'Only comment initiator can delete',
  MUST_HAVE_ONE_SOT = 'Must Have One Sot',
  START_DATE_ONE_HOUR_DIFF = 'Start Date/Time Must Be After One Hour Atleast',
  MUST_HAVE_MULTIPLE_SOT = 'Must Have Multiple Sot',
  EMAIL_CONFIRMED = 'Email Confirmed Successfully',
  EMAIL_LINK_EXPIRED = 'This email link has been expired',
  TWOFACTOR_DISABLED = 'Please Enable Two Factor Authentication First', // both admin and customer
  INVALID_2FA_CODE = '2FA Code Is Invalid', // both admin and customer
  INVALID_PARAMETER = 'Invalid value for parameter',
  ERROR_WHILE_SENDING_EMAIL = 'Error while sending email',
  ADMIN_ID_IS_INVALID = 'Admin ID is invalid',
  DOES_NOT_EXIST = ' does not exist',
  ADMIN_ALREADY_EXIST = 'Admin already exist',
  ACCOUNT_TERMINATED = 'Account terminated',
  SURVEY_EXPIRED = 'Survey has been expired',
  INVALID_APPLICANT_NAME = 'Invalid applicant name',
  INVALID_APPLICANT_COMPANY = 'Invalid company name',
  FAQS_DOES_NOT_EXISTS = 'faqs does not exists',
  FAQ_DOES_NOT_EXISTS = 'faq does not exists',
  NOTICES_DOES_NOT_EXISTS = 'notices does not exists',
  NOTICE_DOES_NOT_EXISTS = 'notice does not exists',
  INVALID_DEVICE_INFO = 'Invalid Device Info',
  SELF_REFERRENCING = 'Self referencing not allowed',
  ATTENDANCE_ALREADY_MARKED = 'Attendance already marked',
  USER_DOES_NOT_EXISTS = 'user does not exists',
  ERROR_CURRENCY_CONVERSION = 'Error In Currency Conversion',
  ERROR_IN_PAYMENT_TRANSACTION = 'Error In Payment Transaction',
  ERROR_IN_DECRYTION = 'Error In Data Decryption',
  EVENT_BANNER_DOES_NOT_EXISTS = 'Event banner does not exists',
  UNABLE_TO_PING_COINMARKET = `Unable to ping coin-gecko market`,

  /**
   * MarketPlace
   */
  AVATAR_ITEM_NOT_EXIST = 'avatar item does not exist',
  INVALID_CATEGORY = 'Invalid category',
  INVALID_ITEM_NAME = 'Invalid item name',
  ITEMS_ALREADY_PURCHASED = 'item already purchased',
  AVATAR_ITEM_NOT_EXIST_IN_CART = 'item does not exist on cart',
  CART_NOT_EXIST = 'Cart does not exit',
  CART_IS_EMPTY = 'Cart is empty',
  /**
   * wishlist
   */
  USER_AVATAR_ITEM_ALREADY_ADDED_TO_WISHLIST = 'user avatar item already added to wishlist',
  WISHLIST_ITEM_DOES_NOT_EXIST = 'wish list item does not exist',
  /**
   * Below are the Admin panel messages
   */
  ADMIN_EMAIL_ALREADY_VERIFIED = 'Email is already verified.',
  INVALID_DATE_DIFFERENCE = 'Invalid date difference. Must be greater than 1 month and less than 12 months.',
  INVALID_UUID = 'Invalid `param` uuid',
  INQUIRY_NOT_EXIST = 'Inquiry does not exist',
  INQUIRY_CAN_NOT_EDIT = 'Inquiry can not edit',
  INQUIRY_CAN_NOT_DELETE = 'Inquiry can not delete',
  ATTACHMENT_CAN_NOT_DELETE = 'Attachment can not delete',
  INVALID_ATTACHMENT_ID = 'Invalid attachment id',
  ATTACHMENT_NOT_EXIST = 'Attachment does not exist',

  UNAUTHORIZED_TO_DELETE_ATTACHMENT = 'Unauthorized to delete attachment',
  MAX_ATTACHMENT_SIZE_ARE_THREE = 'max attachment size are three',
  ADMIN_CREATION_ERROR = 'Amin creation error',
  TWOFA_ALREADY_ENABLED = '2FA already enabled',
  TWOFA_NOT_CONFIGURED = '2FA not enabled',
  INACTIVE_ACCOUNT = 'Account is not active.',
  AVATAR_DOES_NOT_EXISTS = 'Avatar does not exists',
  AVATAR_INPUT_NOT_CONSISTENT = 'Avatar input not consistent',
  AVATAR_ALREADY_EXISTS = 'Avatar already exists',
  INQUIRY_REPLY_NEEDED = 'Reply cannot be empty',
  INVALID_INQUIRY_STATUS = 'Inquiry status cannot move backwards',
  USER_STATUS_ALREADY_EXISTS = 'User status is same as provided',
  PAYMENT_DOES_NOT_EXISTS = 'Payment does not exists',
  PAYMENT_DETAILS_NOT_EXISTS = 'Payment details not exists',
  INVALID_EVENT_STATUS = 'Invalid event status',
  INVALID_AVATAR_BANNER_STATUS = 'Invalid avatar banner status',
  AVATAR_BANNER_DOES_NOT_EXISTS = 'Avatar banner does not exists',
  SILVERBELL_SURVEY_NOT_EXISTS = 'Silver bell survey does not exists',
  INVALID_USER_AVATAR_CATEGORY = 'Invalid user avatar category',
}

// some code enums for sending response code in api response

export enum ResponseCode {
  SUCCESS = 200,
  CREATED_SUCCESSFULLY = 201,
  INTERNAL_ERROR = 500,
  NOT_FOUND = 404,
  CONTENT_NOT_FOUND = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FIVE_LOGIN_ATTEMPT = 600,
  INVALID_USERNAME_OR_PASSWORD = 601, // both admin and customer
  EMAIL_NOT_VERIFIED = 602,
  INVALID_LOGIN_TYPE = 603,
  EMAIL_NOT_REGISTERED = 604, // both admin and customer
  EMAIL_SENDING_ERROR = 605,
  INVALID_VERIFICATION_CODE = 606, // both admin and customer
  VERIFICATION_CODE_EXPIRED = 607,
  USER_ALREADY_EXISTS = 609, // both admin and customer
  REFERRER_NOT_EXIST = 610,
  DEVICE_ALREADY_EXIST = 611,
  MEMBERSHIP_EXPIRY_FOR_SIX_MONTH = 612,
  INCORRECT_CURRENT_PASS = 613,
  SAME_AS_OLD_PASS = 614,
  INVALID_SOT_ID = 615,
  BALANCE_LESS_THAN_REQUIRED = 616,
  UNAUTHORIZED_TO_EDIT_SURVEY = 617,
  IMAGES_ALLOW = 618,
  IMAGE_REQUIRED = 619,
  INVALID_S3_KEY = 620,
  END_DATE_GREATER_THAN_START = 621,
  PHONE_NUMBER_ALREADY_ESXISTS = 622,
  PHONE_NUMBER_DONT_EXIST = 623,
  PHONE_NUMBER_VERIFIED = 624,
  PASSWORD_ALREADY_CREATED = 625,
  INVALID_SURVEY_ID = 626,
  INVALID_INPUT = 627,
  PAYMENT_ALREADY_MAKE = 628,
  FIVE_PHONE_CODE_SEND = 629,
  INVALID_TOKEN = 630, // both admin and customer
  TEMPORARY_BLOCK = 631,
  FIVE_CONFIRMATION_ATTEMPT = 632,
  INVALID_OPTION_ID = 633,
  PARTICIPATED_IN_SURVEY = 634,
  PARTICIPATED_COUNT_COMPLETED = 635,
  INITIATOR_CAN_NOT_PARTICIPATE = 636,
  NOT_PARTICIPATED = 637,
  COMMENT_ALREADY_ADDED = 638,
  COMMENT_NOT_EXIST = 639,
  ONLY_COMMENT_INITIATOR_CAN_DELETE = 640,
  MUST_HAVE_ONE_SOT = 641,
  MUST_HAVE_MULTIPLE_SOT = 642,
  START_DATE_ONE_HOUR_DIFF = 643,
  SURVEY_EXPIRED = 644,
  ACCOUNT_TERMINATED = 645,
  UNABLE_TO_SOCIAL_LOGIN = 646,
  INQUIRY_NOT_EXIST = 648,
  INVALID_ATTACHMENT_ID = 649,
  UNAUTHORIZED_TO_DELETE_ATTACHMENT = 650,
  ATTACHMENT_NOT_EXIST = 651,
  INQUIRY_CAN_NOT_EDIT = 652,
  INVALID_DEVICE_INFO = 653,
  FAQS_DOES_NOT_EXISTS = 654,
  FAQ_DOES_NOT_EXISTS = 655,
  NOTICES_DOES_NOT_EXISTS = 654,
  NOTICE_DOES_NOT_EXISTS = 655,
  SELF_REFERRENCING = 656,
  ATTENDANCE_ALREADY_MARKED = 657,
  MAX_ATTACHMENT_SIZE_ARE_THREE = 658,
  INQUIRY_CAN_NOT_DELETE = 659,
  ATTACHMENT_CAN_NOT_DELETE = 660,
  ERROR_IN_PAYMENT_TRANSACTION = 667,
  USER_DOES_NOT_EXIST = 668,
  /**
   * MarketPlace
   */
  AVATAR_ITEM_NOT_EXIST = 661,
  ITEMS_ALREADY_PURCHASED = 663,
  AVATAR_ITEM_NOT_EXIST_IN_CART = 664,
  CART_NOT_EXIST = 665,
  CART_IS_EMPTY = 666,
  /**
   * wishlist
   */
  USER_AVATAR_ITEM_ALREADY_ADDED_TO_WISHLIST = 662,
  WISHLIST_ITEM_DOES_NOT_EXIST = 663,
  INVALID_SURVEY_OPTION_ID = 664,
  EVENT_BANNER_DOES_NOT_EXISTS = 665,
  /**
   * Below are the Admin panel codes
   */
  TWOFA_DISABLED = 1001,
  TOKEN_EXPIRED = 1002,
  TWOFA_ALREADY_ENABLED = 1003,
  TWOFA_NOT_CONFIGURED = 1004,
  INACTIVE_ACCOUNT = 1005,
  SOT_DOES_NOT_EXISTS = 1006,
  AVATAR_DOES_NOT_EXISTS = 1007,
  AVATAR_INPUT_NOT_CONSISTENT = 1008,
  AVATAR_ALREADY_EXISTS = 1009,
  INQUIRY_REPLY_NEEDED = 1010,
  INVALID_INQUIRY_STATUS = 1011,
  USER_DOES_NOT_EXISTS = 1012,
  USER_STATUS_ALREADY_EXISTS = 1013,
  AVATAR_BANNER_DOES_NOT_EXISTS = 1014,
  PAYMENT_DOES_NOT_EXISTS = 1015,
  PAYMENT_DETAILS_NOT_EXISTS = 1016,
  SILVERBELL_SURVEY_NOT_EXISTS = 1017,
}

export enum LoggerMessages {
  API_CALLED = 'Api Has Been Called.',
}

export enum NodeEnv {
  TEST = 'test',
  DEVELOPMENT = 'development',
  PRODUCTION = 'production',
}

export enum JOB {
  OTP_ATTEMPTS_RESET = 'otp attempts reset',
  LOGIN_ATTEMPTS_RESET = 'login attempts reset',
  LOGOUT_TRUNCATE = 'logout truncate',
  AUTO_LOGIN_TIME_EXPIRY = 'auto login time expiry',
  DELETE_IMAGES = 'delete images',
  WAN_PRICE_TO_USD = 'wan price to usd',
  MSOT_PRICE_TO_USD = 'msot price to usd',
}
